# Generated by Django 4.2.18 on 2025-01-30 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userprofile', verbose_name='comment_user'),
        ),
        migrations.DeleteModel(
            name='Comment1',
        ),
    ]
